import { createSlice } from "@reduxjs/toolkit";

// Initial state of the ad, containing default values for caption, CTA, image mask, URLs, and ad image
const initialState = {
  caption: {
    text: "1 & 2 BHK Luxury Apartments at just Rs.34.97Lakhs", // Default caption text
    position: { x: 50, y: 50 }, // Position of the caption text on the canvas
    max_characters_per_line: 31, // Maximum characters per line for the caption text
    font_size: 44, // Font size for the caption text
    alignment: "left", // Text alignment for the caption
    text_color: "#FFFFFF", // Text color for the caption
  },
  cta: {
    text: "Shop Now", // Default call-to-action (CTA) text
    position: {
      x: 190,
      y: 320,
    }, // Position of the CTA text on the canvas
    text_color: "#FFFFFF", // Text color for the CTA
    background_color: "#0369A1", // Background color for the CTA
  },
  image_mask: { x: 56, y: 442, width: 970, height: 600 }, // Position and dimensions of the image mask
  urls: {
    mask: "https://d273i1jagfl543.cloudfront.net/templates/global_temp_landscape_temp_10_mask.png", // URL for the mask image
    stroke:
      "https://d273i1jagfl543.cloudfront.net/templates/global_temp_landscape_temp_10_Mask_stroke.png?random=12", // URL for the stroke image
    design_pattern:
      "https://d273i1jagfl543.cloudfront.net/templates/global_temp_landscape_temp_10_Design_Pattern.png", // URL for the design pattern image
  },
  adImage:
    "https://blog.logomyway.com/wp-content/uploads/2020/09/KFC-logo.jpg", // Default ad image URL
};

// Creating a slice for the ad with initial state and reducers
export const adSlice = createSlice({
  name: "ad", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to update the background color of the CTA
    adBgColor: (state, action) => {
      state.cta.background_color = action.payload;
    },
    // Reducer to update the ad image
    adImage: (state, action) => {
      state.adImage = action.payload;
    },
    // Reducer to update the caption text
    adText: (state, action) => {
      state.caption.text = action.payload;
    },
    // Reducer to update the CTA text
    adCTA: (state, action) => {
      state.cta.text = action.payload;
    },
  },
});

// Exporting the action creators generated by createSlice
export const { adBgColor, adImage, adText, adCTA, caption, cta, image_mask, urls } = adSlice.actions;

// Exporting the reducer generated by createSlice to be used in the store
export default adSlice.reducer;
